name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '18 4 * * 3'

permissions: read-all

jobs:
  release:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/scanner.yml
    secrets: inherit
