name: Vulnerability scans

on:
  workflow_call:

  workflow_dispatch:

permissions:
  contents: read

# description: |
#   A fast vulnerability scan on the repo that effectively supplements ossf scorecard and codesql
#   and may run every day.
#
#   * trivy reports are often more easily actionable than codeql reports.
#   * govumnscan supplements this analysis with a more go-specific approach
#
# NOTE: at this moment, we don't want to adopt snyk, which requires a token, provides an extra dashboard etc.
# Most likely, snyk would be redundant with trivy.

jobs:
  analysis:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      -
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      -
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: stable
          check-latest: true
          cache: true
      -
        name: Vulnerability scan by trivy
        uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # v0.34.0
        with:
          scan-type: repo
          format: sarif
          hide-progress: false
          output: trivy-code-report.sarif
          scanners: vuln,secret
          version: v0.68.1
          exit-code: 0
      -
        name: Upload trivy findings to code scanning dashboard
        uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
        with:
          category: trivy
          sarif_file: trivy-code-report.sarif

  govulnscan:
    name: go vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      -
        id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          output-format: sarif
          output-file: govulnscan-report.sarif
      -
        name: Upload govulnscan findings to code scanning dashboard
        uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
        with:
          category: govulnscan
          sarif_file: govulnscan-report.sarif
